language: node_js
node_js: 
  - "6.0.0"

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo clean && hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "huangsansui"
  - git config user.email "674208615@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${blog}@${GH_REF}" master:master
  - hexo d
# E: Build LifeCycle

branches:
  only:
    - backup
env:
 global:
   - GH_REF: github.com/huangsansui/huangsansui.github.io

